name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Conda and include $CONDA in $PATH
      run: |
        conda update -n base -c defaults conda
    - name: Install dependencies
      run: |
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda create -y -p ~/bag
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda activate ~/bag
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda install --file requirements.txt
    - name: Lint with flake8
      run: |
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        eval "$(${CONDA}/bin/conda shell.bash hook)" && conda install pytest
        pytest
